# Generated by Django 3.2.13 on 2022-06-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_tickets_search', '0004_auto_20220607_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
