# Generated by Django 3.2.13 on 2022-06-07 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_tickets_search', '0005_auto_20220607_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='available',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='reserved_number_of_seats',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='total_number_of_seats',
        ),
        migrations.AddField(
            model_name='tickets',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='air_tickets_search.flights'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flights',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
