# Generated by Django 3.2.13 on 2022-06-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_tickets_search', '0008_auto_20220607_1239'),
    ]


