# Generated by Django 3.2.13 on 2022-06-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_tickets_search', '0009_auto_20220607_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
