# Generated by Django 3.2.13 on 2022-06-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_tickets_search', '0010_auto_20220608_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
