# Generated by Django 3.2.13 on 2022-06-15 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('air_tickets_search', '0011_auto_20220608_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights_bought',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
